version: "3.8"
# Please note that this docker compose is using the deploy-check tron container
# which is separate from the "real" container that's used to deploy tron.
services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile.anvil
    environment:
      FOUNDRY_PROFILE: docker
      RUST_LOG: backend,api,node,rpc=warn
    restart: unless-stopped
    ports:
      - "8545:8545"
  tron-setup:
    depends_on:
      - anvil
    build:
      context: .
      dockerfile: Dockerfile.deploymentCheck
    environment:
      FOUNDRY_PROFILE: docker
