version: "3.8"
services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile
      target: anvil
    restart: unless-stopped
    ports:
      - "8545:8545"
  deploy:
    depends_on:
      - anvil
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-tron
    entrypoint:
      - /bin/sh
      - -c
    command:
      - ./docker-scripts/deploy-tron.sh && /usr/bin/tail -f /dev/null
