apiVersion: batch/v1
kind: Job
metadata:
  name: necessist
  namespace: dev
spec:
  template:
    metadata:
      name: necessist
    spec:
      containers:
        - name: necessist
          image: {{NECESSIST_IMAGE_TAG}}
      restartPolicy: Never

