apiVersion: v1
kind: Service
metadata:
  labels:
    app: anvil-deploy-check
  name: anvil-deploy-check
  namespace: dev
spec:
  ports:
    - port: 8545
      protocol: TCP
      targetPort: 8545
  selector:
    app: anvil-deploy-check
  type: ClusterIP
