apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anvil
  name: anvil
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: anvil
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: anvil
    spec:
      containers:
      - env:
        - name: FOUNDRY_PROFILE
          value: docker
        - name: RUST_LOG
          value: backend,api,node,rpc=warn
        - name: CHAIN_ID
          value: "31338"
        image: {{ECR_REPOSITORY}}
        imagePullPolicy: Always
        name: anvil
        ports:
        - containerPort: 8545
          protocol: TCP
