apiVersion: v1
kind: Service
metadata:
  labels:
    app: anvil
  name: anvil
  namespace: {{NAMESPACE}}
spec:
  ports:
  - port: 8545
    protocol: TCP
    targetPort: 8545
  selector:
    app: anvil
  type: ClusterIP
