name: Merge external branch to internal

on:
  push:
    branches:
      - external

jobs:
  merge_forward:
    name: Merge and Push
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: internal
          ssh-key: ${{ secrets.SSH_KEY }}
          fetch-depth: "0"

      - name: Set GIT name and email
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@thrackle.io"

      - name: Merge and push
        run: |
          echo "Merging external -> internal"
          git merge --no-edit external
          git push
