name: Test

on:
  push:
    branches:
      - main
      - internal
      - external
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Demo Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-09fe3e041369a816365a020f715ad6f94dbce9f2

      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          make install
      - name: Build
        run: |
          make build
      - name: Demo
        run: |
          sh script/demo/DemoSetup.sh
