name: Deploy

on:
  workflow_dispatch:
    inputs:
      ETH_RPC_URL:
        description: "Blockchain RPC URL"
        type: string
        required: false
  push:
    branches:
      - main
  workflow_call:
jobs:
  Deploy:
    runs-on: ubuntu-20.04
    environment: Development
    env:
      PIPELINE_ETH_RPC_URL: ${{secrets.ETH_RPC_URL}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          make install
      - name: Deploy
        id: deploy
        run: |
          make deployAllPipeline
      - name: deploy resume
        if: ${{ failure() && steps.deploy.conclusion == 'failure' }}
        run: |
          make deployAllPipelineResume
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: S3 Upload
        run: aws s3 sync /home/runner/work/Tron/Tron/broadcast/ s3://anvil-uploaded-contracts/pipeline-artifacts/
      - name: Archive run_latest.json
        uses: actions/upload-artifact@v3
        with:
          name: broadcast
          retention-days: 8
          path: |
            /home/runner/work/Tron/Tron/broadcast/*
