name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # May 2, 2024 - Must be a release (nightly) tag
          version: nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9 
      - name: Generate documentation
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          rm -rf docs/src/src
          forge doc
          git add .
          git commit -m "Generate documentation"
          git push
