# Necessist is a testing tool, which modifies Solidity tests,
name: Run Necessist Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # OIDC to allow push to ECR

jobs:
  build-and-push-images:
    runs-on: Linux-Arm64
    outputs:
      necessist_image_slug: ${{ steps.register-image.outputs.necessist_image_slug }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # A limited push-to-ECR IAM role exists in the target environment, allowing GitHub ODIC
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine Git Tag or Use Commit SHA
        id: determine-git-tag
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* || -n "${{ github.event.release.tag_name }}" ]]; then
            echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "GIT_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      # Per https://github.com/orgs/community/discussions/26636, outputs cant contain a secret, but ECR URIs do.
      - name: Register Image Names
        id: register-image
        run: |
          necessist_image_slug="necessist/forte-rules-engine:${{ env.GIT_TAG }}"
          echo "NECESSIST_IMAGE=${{ secrets.ECR_REGISTRY }}/${necessist_image_slug}" >> $GITHUB_ENV
          echo "necessist_image_slug=${necessist_image_slug}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image - Necessist
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          file: Dockerfile
          target: necessist
          tags: ${{ env.NECESSIST_IMAGE }}

  deploy-necessist:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - name: Echo outputs
        run: |
          echo "Necessist Image: ${{ toJson(needs) }}"

      - name: Trigger Necessist Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: "${{ secrets.WORKFLOW_DISPATCH_TOKEN }}"
          repository: thrackle-io/application-infrastructure
          event-type: necessist-deployment-dispatch
          client-payload: |
            {"image_slug": "${{ needs.build-and-push-images.outputs.necessist_image_slug }}"}
