name: Test

on:
  push:
    branches:
      - main
      - internal
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest-m-16

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          forge install

      - name: Build
        run: |
          forge clean && forge build --optimize

      - name: Test
        run: |
          forge test -vv --ffi --no-match-path "*invariant*"
      - name: Test Invariant
        run: |
          forge test -vv --ffi --match-path "*invariant*"